stages:
  - lint
  - deploy

lint:awesome-lint:
  image: pipelinecomponents/awesome-lint
  script:
    - awesome-lint README.md
  stage: lint

pages:
  image: python:latest
  script:
    - pip install mkdocs
    - pip install mkdocs-material
    - mkdir docs
    - cp README.md docs/index.md
    - cp CONTRIBUTING.md docs/contributing.md
    - cp CREDITS.md docs/credits.md
    - cp LICENSE docs/license.md
    - mkdocs build -d public/
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    - master
